---
title: "20191008-case_study"
author: "Jared Garfinkel"
date: "10/8/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")


library(tidyverse)
library(p8105.datasets)



library(ggridges)
library(tidyverse)
library(viridis)

options(
  ggplot2.continous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
data(nyc_airbnb)
str(nyc_airbnb)
```

* how are airbnb prices related to rent in the neighborhood?

* which neighborhood has the most expensive and which the least?

* do hosts with multiple sites have higher prices or ratings?

* does price have any relation to ratings?

* Is average lenth of stay related to neighborhood? price? etc?

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = neighbourhood_group)) +
  geom_point()
```

```{r, fig.width = 8}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Brooklyn") %>% 
  ggplot(aes(x = price)) +
  geom_histogram(bins = 250)
```

```{r}
nyc_airbnb %>% 
  group_by(neighbourhood_group, room_type) %>% 
  summarize(med_price = median(price, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = med_price
  )
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Staten Island", room_type == "Shared room")
```


```{r}
nyc_airbnb %>% 
  count(neighbourhood_group, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```

```{r, eval = FALSE}
nyc_airbnb %>% 
  group_by(neighbourhood_group) %>% 
  summarize(
    mean_price = mean(price, na.rm = TRUE),
    mean_review = mean(review_scores_location, na.rm = TRUE)) %>% 
  ggplot(aes(x = mean_review, y = mean_price)) +
  geom_point() +
  facet_grid(~neighbourhood_group)
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood)
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood == "Astoria") %>% 
  ggplot(aes(x = review_scores_location, y = price)) +
  geom_point()
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan",
         price < 1000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = .3) +
  facet_grid(~room_type)
```

```{r, eval = FALSE}
nyc_airbnb %>% 
  filter(
    borough == "Manhattan",
    price > 2000)
  leaflet() %>% 
  addTiles() %>% 
    addMarkers(~long, ~lat)
```

